connector.name=postgresql
connection-url=jdbc:postgresql://analytics-postgres-rw:5432/analytics?sslmode=disable
connection-user=trino_ro
connection-password=changeme-analytics-pg
case-insensitive-name-matching=true
