apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trino-worker-spill
  labels:
    app.kubernetes.io/name: trino
    app.kubernetes.io/component: worker
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: qks-ceph-cephfs
  resources:
    requests:
      storage: 200Gi
